apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: ingress
spec:
  encryptedData:
    cloudflare_api_token: AgAMmzH9GRM98YdVwhlcu8JXseTvlQIVz0/ys+Sqd2HL1ZSgIhRJxlpFrcVX0V4P3S7DhvVNZqwLq/BaTR9dKns0KiEX0hQYdT5401M87+YKdv6rjY+ButdYbWrRK4ATSeUzryO0jGjlQR0rjMdNPClHH9x2ErJyy8XCeRYfzJCVb1BYyE/WGgT5lM7oS5KBcPlucY8QhVuyphH1n6G12hjCPFTjRxGUJImgqDd+75rK8S0a0oYjHH47aYCs4rWgp605Mea4TJZTiA+J8Ep2mS6O0Avcr0B+Un7s6b1sVpieHN/MHjeOiaEoWkX/kyIleg12Fia3ikNqiLhQIG689AZcIhJAYXJacmiLxDdyzMC72k+3m+Hv/XtXwNM3GoymF6mLIKNAVHGejxRwdXsdR8GUkU6l1EFlbJsCjQ7542Tcny3pfs5B4CdJbyktvmD8aJraZGPnXI3wyJZS3YXhDORpXsE+83zEJap/aRjy6m5qRqrn9hPjlR+YihMPKQENE9VTL7A7jDNlhLEUxF2DcRHgBcpFU6ENID6a86OQidmmGsX4T859oC8lfbxQPv8a1xTcTM5vnYS9JVi74NirIZMYQHbuSOTAA5dxgs2IC8p0rUc94zc+/EmBbsjSU5vLiiDRkZFHYZnV81I0uYA1PNtvkKurctfsv3UAZ0pyOWBi5FPpQnHIDtcTYzTb64DIVm7pbrkqC/VgLXwUyEqbhs1vLvncyaAKJMCvqbqRLiTwnW5pZHl7XtjI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: ingress

