apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: ingress
spec:
  encryptedData:
    cloudflare_api_token: AgBgVqUtrkNMMKLBMh0y8Et9WYdDQ/kPWaKC+UNXicG8Dw7lXdiLcj+nJpkv/6w7XTO7r0vhefLZrdtu866RLhrZ1atc7lNXmO7S5uMDEtYvg+Y1S8uve1zkSjT7YnBCJn+IV+N36cYPo5cnE/Zf8obGFh5zpQx/dBl3dgJg043fgVAI6HtSQHu2AT1iGKjoOieYfPbUSgKQZNpttkK2jJ1i0XyFCVW+BP29++Rsite+tHBf1NB6vVP9L4dV/DJY8kUcCe2YQieFgYiIAUmYBfDJO1IWHSC8q7wZekIIUtK1S4wYUXGgI4FK7dDqIGjsNG6PKM2rgkB3y9js61KuopkUwMiysYconJ9NJcaZF23RnrFkRGcqgjjTMtRioQndHNvMCZQyx6Rh6yhfY6zsV+kijTlZx4WLra/ZpscpUVpRy4GbMnglvxwqabrDzsCFHTzuuaYCZdJTL36MlL/ggzB3SFTkDuURnzLiObzU8l6b/m/hSm10hortl5DHCmXWtQMP66Ufgx4oXgLuMOoMXQpHXyN1dmxk6Q8J7CLVZVP1S264rZf8/YkwfvLWWJg4MoRr9Tx/J5rRj0H7JI2SRVYJ4+wnIQM0QmVdcpxd15f3YRIqLI6hlWglyjDeCycY3eG8baN3oZx8MzTq7u4dACm5KlZO8x9lXvzDABUaHNCB0FhcNAbXOA6UGS8RF8Thg8b6nlXvRh+6QrlGfng09vTJOL12jcjJzeCzcwMKFuFO3dRzm7hla51L
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: ingress

