resources:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: testing-1
    data:
      key1: value1
      key2: value2
  - apiVersion: v1
    kind: Secret
    metadata:
      name: testing-2
    stringData:
      key1: value1
      key2: value2
