apiVersion: v2
type: application
name: runners
sources:
  - https://github.com/mjpitz/mjpitz/tree/main/charts/drone
maintainers:
  - name: Mya Pitzeruse
    url: https://mjpitz.com
version: 0.0.0
appVersion: latest
dependencies:
  - name: digitalocean
    version: "*"
    condition: digitalocean.enabled

  - name: kubernetes
    version: "*"
    condition: kubernetes.enabled
