{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-queue.fullname" . }}-config
data:
  redis.conf: {{ include "redis-queue.config" . | b64enc | quote }}
{{- end }}
