---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-queue.fullname" . }}
  labels:
    {{- include "redis-queue.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
    - port: 9121
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "redis-queue.selectorLabels" . | nindent 4 }}
