---
# Source: 12factor/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 12factor-autoscaling
  labels:
    helm.sh/chart: 12factor-22.5.9
    app.kubernetes.io/name: autoscaling
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
---
# Source: 12factor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 12factor-autoscaling
  labels:
    helm.sh/chart: 12factor-22.5.9
    app.kubernetes.io/name: autoscaling
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: autoscaling
      app.kubernetes.io/instance: 12factor
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        helm.sh/chart: 12factor-22.5.9
        app.kubernetes.io/name: autoscaling
        app.kubernetes.io/instance: 12factor
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: 12factor-autoscaling
      containers:
        - name: app
          image: "nginx:"
          imagePullPolicy: IfNotPresent
---
# Source: 12factor/templates/hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: 12factor-autoscaling
  labels:
    helm.sh/chart: 12factor-22.5.9
    app.kubernetes.io/name: autoscaling
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 12factor-autoscaling
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
