# -- These are included out of box.
imagePullSecrets:
  - registry: ghcr.io
    username: username
    password: password

deployment:
  # -- These are additional.
  imagePullSecrets:
    - name: external-image-pull-secret

  tasks:
    - name: app
