---
# Source: 12factor/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 12factor-array-env
  labels:
    helm.sh/chart: 12factor-24.1.0
    app.kubernetes.io/name: array-env
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
---
# Source: 12factor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 12factor-array-env
  labels:
    helm.sh/chart: 12factor-24.1.0
    app.kubernetes.io/name: array-env
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: array-env
      app.kubernetes.io/instance: 12factor
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        helm.sh/chart: 12factor-24.1.0
        app.kubernetes.io/name: array-env
        app.kubernetes.io/instance: 12factor
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: 12factor-array-env
      containers:
        - name: app
          image: "nginx:"
          imagePullPolicy: IfNotPresent
          env:
            - name: KEY_1
              value: VALUE_1
            - name: KEY_2
              value: VALUE_2
---
# Source: 12factor/templates/cronjobs.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: 12factor-array-env-task-app
  labels:
    helm.sh/chart: 12factor-24.1.0
    app.kubernetes.io/name: array-env
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: 
  suspend: 
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: task-app
        helm.sh/chart: 12factor-24.1.0
        app.kubernetes.io/name: array-env
        app.kubernetes.io/instance: 12factor
        app.kubernetes.io/managed-by: Helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: task-app
            helm.sh/chart: 12factor-24.1.0
            app.kubernetes.io/name: array-env
            app.kubernetes.io/instance: 12factor
            app.kubernetes.io/managed-by: Helm
        spec:
          serviceAccountName: 12factor-array-env
          restartPolicy: Always
          containers:
            - name: app
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
              image: "nginx:"
              imagePullPolicy: IfNotPresent
              env:
                - name: KEY_1
                  value: VALUE_1
                - name: KEY_2
                  value: VALUE_2
