---
# Source: 12factor/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 12factor
  labels:
    helm.sh/chart: 12factor-22.5.9
    app.kubernetes.io/name: 12factor
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
---
# Source: 12factor/templates/dockerconfig.yaml
apiVersion: v1
kind: Secret
metadata:
  name: 12factor-pull-secrets
  labels:
    helm.sh/chart: 12factor-22.5.9
    app.kubernetes.io/name: 12factor
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkWE5sY201aGJXVTZjR0Z6YzNkdmNtUT0iLCJwYXNzd29yZCI6InBhc3N3b3JkIiwidXNlcm5hbWUiOiJ1c2VybmFtZSJ9fX0="
---
# Source: 12factor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 12factor
  labels:
    helm.sh/chart: 12factor-22.5.9
    app.kubernetes.io/name: 12factor
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: 12factor
      app.kubernetes.io/instance: 12factor
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        helm.sh/chart: 12factor-22.5.9
        app.kubernetes.io/name: 12factor
        app.kubernetes.io/instance: 12factor
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: 12factor-pull-secrets
        - name: external-image-pull-secret
      serviceAccountName: 12factor
      containers:
        - name: app
          image: "nginx:"
          imagePullPolicy: IfNotPresent
---
# Source: 12factor/templates/cronjobs.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: 12factor-task-app
  labels:
    helm.sh/chart: 12factor-22.5.9
    app.kubernetes.io/name: 12factor
    app.kubernetes.io/instance: 12factor
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: 
  suspend: 
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: task-app
        helm.sh/chart: 12factor-22.5.9
        app.kubernetes.io/name: 12factor
        app.kubernetes.io/instance: 12factor
        app.kubernetes.io/managed-by: Helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: task-app
            helm.sh/chart: 12factor-22.5.9
            app.kubernetes.io/name: 12factor
            app.kubernetes.io/instance: 12factor
            app.kubernetes.io/managed-by: Helm
        spec:
          imagePullSecrets:
            - name: 12factor-pull-secrets
            - name: external-image-pull-secret
          serviceAccountName: 12factor
          containers:
            - name: app
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
              image: "nginx:"
              imagePullPolicy: IfNotPresent
