apiVersion: v1
kind: Secret
metadata:
  name: {{ include "12factor.fullname" . }}-env
data:
  PAGES_ADMIN_USERNAME: {{ .Values.pages.config.admin.username | b64enc }}
  PAGES_ADMIN_PASSWORD: {{ .Values.pages.config.admin.password | b64enc }}
  PAGES_ADMIN_TOKEN: {{ printf "%s:%s" .Values.pages.config.admin.username .Values.pages.config.admin.password | b64enc }}
  PAGES_SITE_FILE: {{ "/etc/pages/conf/pages.toml" | b64enc }}
