apiVersion: v1
kind: Secret
metadata:
  name: {{ include "12factor.fullname" . }}-secret
stringData:
  pages.toml: |
    {{- range .Values.pages.config.sites }}
    [sites.{{ .domain | quote }}]
    url = {{ .url | quote }}
    branch = {{ .branch | quote }}
    syncInterval = {{ .interval | quote }}
    {{- end }}
