{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "12factor.fullname" . }}
  labels:
    {{- include "12factor.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.metrics.serviceMonitor.interval }}
      path: /metrics
      port: debug
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "12factor.selectorLabels" . | nindent 6 }}
  {{- end }}
