apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_token: AgCfDg1PVhsg+dYF/ch52V8tuBtL86vGwk8+/OxF0V/kT/osPSyGPCCxohYBlvFRuZUhdXGtuh/aKlNu/CycfUcBIeBTxYm1PBba9RMZlZzHVN3bhLPptKk/WOqR+mlMBgVzYrmF4YVTWM1bodDcl/8G0flNz/rLZcbTmebjFYGLE5EnjFDreJH0gQGumXYLJlLKxoas7oiNDoHfuDCzNzLA+koSOEo2PerdL/OQME8VazZQbfL2Zcza5yOhvCxsZU06Q+aF/m92Lw8ebVSjDfg/7ygLUug3P5vxNeO6lBzmf6bivki8cOhvZshaWiwx1tztBxJ9eeUant6avTOIIAFal9JdwW3NhbS7l5jfVLVN0vyox3A+AmppGBUh6V7itLr2E4Ka3DJop2Ettm9Hq/wkAdH4ZWw9EBK/RSDjD+/BF+GwIjl365p7fbiAp76dhyGdcsbJ80+ZVc1Iun3WmyGHdHM2GDQgLawOjPHxY27G7XTv1v8zBFzIWyn6eGXbfJ5At/UqXIOE54kYxyV/kB1yRerbkcmtqaBBvS5JJ51UaFXoMmP8ranvJCPiXtjP3Fftxb6fbGKzVVwokNWjF2I13xGrgQXkJ4mwxJKDQZj2iPYIFynbCBIYF6/0hR2EeoTrnCpsbDjYRbXP0n3Gqpjh4+LZjo/zXZtsKJuxweWluKNPV1RGTPBeCY2q5wLwwKBZcK/pHxlagU0XQ93HhND+pSSEV93fNYtTX5C6h4hylMroQ9NH2k4j
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

