apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_token: AgCs9wI5a4lQUUe6S6ka2GRBXtVmTZuAa0+HXf4xk0UzJ/ehisDR+tqDzGvbetICSy9PMJLwDybNWyy9Bu2mxlJQO0IV2St37XsDz90jeLadHXGkoNsYzIF57DcQ19LaUx6OelNFiSl9hKTNcHXQHd6WIMjdUvqhREgQxzWveUx4cJKqY4zl6QT3aWmMfQzb60Xnp9sqkwsvJfrcAL5SmWwt+wbpe6+NIua5Ny6fpOsRYtxHvn0qhrp9Lr/qCULhwTSg7OAKcjwb9mV6zkH0Gl9IUzrxwqMLITkeLsJb596jaWp91rzqVHL//LSIduqXWFVDUk6z7dQklqQ8uX5c2R0OtJFrP23eEcINBqC/kJaCjQ8Afft4tnMWMVHSPgjmIYO/7IYGEyPr51XPyXw06EQkyOIyu6yQI3Au0OSm2cxGB2iQlYve/pWSGR6hvsz5qLA9u3YH+VMyWZzQYuim8MWqQP0D9mZdH1p+e+XD5m9IXYlaLLwTgVfY4ocWhdYsakhAJzNsS5MFr7MIU4Z2iuqzK2wdh1lwCt6ZZfFkD1yBm9OJddYwjPWN+70XHD2KbOnZxKard2uf3X4Y7XO0SkW8MfYkOe1KshUrZ/BOLhZYvht5zuis0x/x0a/UeUORpG/7bJlheJUAXTpMYUGeOVmf9lqCY8rfcB8jfrbGggBJy6x3xFyZoZYIHlT+dxZj0VUi9tlRZacUl2StbRSYSM80XkDpbmTFbdw626qrM94Oc4AwRBQ+Fij3
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

