apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: maddy-tls
spec:
  secretName: maddy-tls
  dnsNames:
    - {{ .Values.maddy.config.domains.mx }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
