# Documentation: https://googleapis.github.io/genai-toolbox/resources/sources/
# sources:
#   otel:
#     # We use the MySQL connector here because the PostgreSQL one doesn't support sslmode=disable
#     kind: mysql
#     host: metrics-clickhouse
#     port: 9004
#     database: otel
#     user: clickhouse
#     password: clickhouse

# Documentation: https://googleapis.github.io/genai-toolbox/resources/tools/
# tools:
#   search_flights_by_number:
#     kind: postgres-sql
#     source: my-pg-instance
#     statement: |
#       SELECT * FROM flights
#       WHERE airline = $1
#       AND flight_number = $2
#       LIMIT 10
#     description: |
#       Use this tool to get information for a specific flight.
#       Takes an airline code and flight number and returns info on the flight.
#       Do NOT use this tool with a flight id. Do NOT guess an airline code or flight number.
#       An airline code is a code for an airline service consisting of a two-character
#       airline designator and followed by a flight number, which is a 1 to 4 digit number.
#       For example, if given CY 0123, the airline is "CY", and flight_number is "123".
#       Another example for this is DL 1234, the airline is "DL", and flight_number is "1234".
#       If the tool returns more than one option choose the date closest to today.
#       Example:
#       {{
#           "airline": "CY",
#           "flight_number": "888",
#       }}
#       Example:
#       {{
#           "airline": "DL",
#           "flight_number": "1234",
#       }}
#     parameters:
#       - name: airline
#         type: string
#         description: Airline unique 2 letter identifier
#       - name: flight_number
#         type: string
#         description: 1 to 4 digit number

#   authenticated_parameters:
#     kind: postgres-sql
#     source: my-pg-instance
#     statement: |
#       SELECT * FROM flights WHERE user_id = $1
#     parameters:
#       - name: user_id
#         type: string
#         description: Auto-populated from Google login
#         authServices:
#           # Refer to one of the `authServices` defined
#           - name: my-google-auth
#           # `sub` is the OIDC claim field for user ID
#             field: sub
  
#   template_parameter_example:
#     kind: postgres-sql
#     source: my-pg-instance
#     statement: |
#       SELECT {{array .columnNames}} FROM {{.tableName}}
#     description: |
#       Use this tool to list all information from a specific table.
#       Example:
#       {{
#           "tableName": "flights",
#           "columnNames": ["id", "name"]
#       }}
#     templateParameters:
#       - name: tableName
#         type: string
#         description: Table to select from
#       - name: columnNames
#         type: array
#         description: The columns to select
#         items:
#           name: column
#           type: string
#           description: Name of a column to select
