apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-raft.fullname" . }}
  labels:
    {{- include "redis-raft.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "redis-raft.fullname" . }}
  selector:
    matchLabels:
      {{- include "redis-raft.selectorLabels" . | nindent 6 }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            {{- .Values.persistence.resources | toYaml | nindent 12 }}
        {{- with .Values.persistence.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "redis-raft.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redis-raft.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
          args:
            - |
              echo $HOSTNAME | \
                  sed 's:{{ include "redis-raft.fullname" . }}-::g' | \
                  xargs -I{} env REDIS_RAFT_MODULE_ID=1{} sh docker-entrypoint.sh \
                  /redis/etc/redis.conf
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - /redis/etc/postStart.sh
                  - {{ include "redis-raft.fullname" . }}
                  - {{ include "redis-raft.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:6379
            preStop:
              exec:
                command:
                  - sh
                  - /redis/etc/preStop.sh
                  - {{ include "redis-raft.fullname" . }}
          volumeMounts:
            - mountPath: /redis/etc
              name: etc
            - mountPath: /redis/data
              name: data
        - name: redis-exporter
          image: quay.io/oliver006/redis_exporter:v1.35.1
          ports:
            - name: metrics
              containerPort: 9121
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: etc
          configMap:
            name: {{ include "redis-raft.fullname" . }}
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
