apiVersion: v2
name: registry
description: Deploy a container registry to Kubernetes using Helm.
type: application
version: 22.3.0
appVersion: 2.8.0
dependencies:
  - name: auth
    repository: "file://../auth"
    version: "*"
    condition: auth.enabled
  - name: redis
    repository: "file://../redis"
    version: "*"
    condition: redis.enabled
  - name: storj
    repository: "file://../storj"
    version: "*"
    condition: storj.enabled
