apiVersion: v2
type: application
name: registry
description: |
  Easily deploy and configure a production-ready container registry backed by your favorite cloud storage provider. 
  Optionally add a highly-available, partition-tolerant Redis cache that's fronted by Envoy.
sources:
  - https://github.com/distribution/distribution
  - https://github.com/mjpitz/mjpitz/tree/main/charts/registry
maintainers:
  - name: Mya Pitzeruse
    url: https://mya.sh
version: 22.4.9
appVersion: 2.8.0
dependencies:
  - name: auth
    repository: https://mya.sh
    version: 22.4.1
    condition: auth.enabled
  - name: redis
    repository: https://mya.sh
    version: 22.4.7
    condition: redis.enabled
  - name: storj
    repository: https://mya.sh
    version: 22.4.3
    condition: storj.enabled
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: FD0F1E353074E15A4883BC630FCA5E3C09DFB314
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0fca5e3c09dfb314
