apiVersion: v2
type: application
name: registry
description: |
  Easily deploy and configure a production-ready container registry backed by your favorite cloud storage provider. 
  Optionally add a highly-available, partition-tolerant Redis cache that's fronted by Envoy.
sources:
  - https://github.com/distribution/distribution
  - https://github.com/mjpitz/mjpitz/tree/main/charts/registry
maintainers:
  - name: Mya Pitzeruse
    url: https://mjpitz.com
version: 22.4.1
appVersion: 2.8.0
dependencies:
  - name: auth
    repository: https://mjpitz.com
    version: 22.4.0
    condition: auth.enabled
  - name: redis
    repository: https://mjpitz.com
    version: 22.4.2
    condition: redis.enabled
  - name: storj
    repository: https://mjpitz.com
    version: 22.4.1
    condition: storj.enabled
