apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: grafana-env-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgApP/hpyi+WJCcUt81FDQ8zMCgHMN1fg7nJt+a3mZ6hI9Dk8rBU5ampyF+az5Gn2yc3dCiS3IBp4ocKnxKXf+uRi8VoZcgQZwK1hozeq6oTXchRNM0psCeji/VAItfm0Gg+ufoR3ZlV+Qh/dTVQK4kmSPpFG/r8eqth38b5cHXt8riERZJeN4I5noKRGzzN/a1smvxjdY1DlT6sqPKiwtZf5HcPBwFzWlS9Walf8UHQkAa73zbhiOyDMi9WLq/QZReNNdCxLvFzUOWDKcYVYkBaAVBaigKnkM58HATUjNL4T3BKjbqC9mzSJZ6H60X5LGL5bPrlapj24FKcabyWXHJoy5ILUt9Ed8vjbB7GeZRY1D7z85ldLrQDBmN7aTNufokbnpclrLqk4e68IPG+uRE0Hv4msX/M+bcbD0u6RYrFZSr/3lfJiN6VlBdG/S5oWYqbFezrqZlgrEIQ9NrwRPCETnhYdTb3v+A4WHt/HLhB5G5OlhVUBr6bvtbzGyKk4RMtIeIAdcfNiWcYKIn8YfNrdQiPP6r0HyZE6a06igCCTpss/J15mHBCh/zXdjEG4/tP5EWbYjXCM4Ve3AZzF/Y9ZXi0DM22u2ciuFNmxtPfMD1EkttgTPISz2FzuBkQ9CywBcAen0hToXk8u5Rm2RW5Dcz5+Es8kb79ylp3orynZzufro9yH7GyA/nsuzSyFnhR5ZqU3bsrSJu2sQr7NQZerAOv6g==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgBimnpVPRpHCuDClNaRkRQhmdjLYiyByPhvwn8jB1nhxZ0x7IqzOpxGDXNgJyrPM4uFmqFaz04yKoQAW2XaORLUC5FlTKAVjzQeTke6J7lIUw7iOQADgEOaE6dBz8Yr8O/63HVYjCqga6iRwtu9JWDUic/3AFS/BvmDePnWoejgu5olhaUfdLm7dcBEv9WC5xdGC/VQRYO1UojsUuYBUqWYk7w1hnoNR/2XNsBQkLsI/vMjWmEnh4RSy6X0dGfOj5D3x9hZTBU1ejrDMh01tqn8CEKh8JicYOhAHC9vCMcfkv+gstG5Ddg3UCHdughEV60y4cxmgtQlgg/ItV0Bw3PW9KIKGGD4DIau4G8A7lMa5nkCywZFO5IdDOT2ySq/DtJijU10lYj+S28lQvZUxYNipQfFJ6250j8drZFYaytebZLUuL8i4ct4idIocqioi8HfghB0RhH7bqXTvVc+7M86Kn9CesLisJgxXtECh24FoExCcbwRVhFXrw1QO9kx8yJZTkmLQ/lS+pbdu4eG5F+xcKKqBBGCKaBPsnpccZCvxyS1B8pjQKGLJ8pKsFnND+9VmppeJCX76+HRj3Zj4M9NPvsAhRHDQhFbdyha7fTskJCCpQyXrtm8/5vo3QEXOQ+lh1a8t1s3cA9JMB+aFX4n4C5GqfE6vfnJIRSqpMO8Kysdc4zVQrd02/Yp00n9/Q0NLEsWSpegpeS2ZaSF+5f4Uj67d3qL0yI0k7fxiOv58guFWGwbMYUl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: grafana-env-secrets
      namespace: monitoring

