apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: grafana-env-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgCkDhJvWhpiCFSWtuEIwCofZdDaoy5f/pxjkKpOLa//E2IDl5t1qubYKHGjmcLeqpO0VhWwCg7tdczawTzZ6rwxlX3+8/d3GyRz7jgnOuVSXPiB2kmkxF6/pGvHCmVOhDcGt80UP7sGUtFCrUmIPJPoE1HNif69SOfdYwaouA+akNgUnA2WrN+a4n7/i+VjxLDile/5GPBRp2O2QMwGnM6pw6yPadfiPLxNmZpE+fb5tU6w6PDHTN3gXAQrGx+33rddkOF4HBnSk84tpVCWEMytVzDh2iGzMjQQvM4tJHA23Ncn3XSSlqylnvG1fqaPamqDAG002baa7joMpNEzgBKZ4eWvAQLxn0XX0ESzW/JrAF1io6SQYefUJ4RhsAyNiCl2utHxbC1vEgSSJMG7SFtqAZnDPyL7Ef6mAcrDtnAS4Oo4GK3W1OIcy7w89Nnn3aFlY80qOAm05NVwi/hxp9jRc3PRK5iH5Y7r92Dx+o2wCspnaNWVPLhaIAoW2/Ekoh92VT55pu4W2qEAB/VWD3CfvaF5H56GUnY1T9QybHeWKl9pDS6QcPHLpsg6vbzGPhkDPdwmP/fYh/h79n8WjenWQdBoBDzc4IOog12yf7hZnKDGXTyVx2KVExlLJXcCALI0ecio0QDLL8Ae2A6vzrXd/ur5HOs96EvwU0ol4NgIRB4TTfCCaqg7XW9fpJXv6Q0gvfqqCSV4iX4Wv0A1FJMSjy+zaN7PHNozMipO0/pZ2TJKGuo=
    GF_AUTH_GITHUB_CLIENT_SECRET: AgARDzsKMbT48/BGDQlGueWbDkbsG1JgQ0QDMfYxNgBTetLkn6jcWuaH4sHIWEuZTOHOofD8TCYVaFNeUsPb40WnI/YPBbJj4shySSa5noIOkpKa21N5Dj9NkQum8ziyfT/jHyLZlOcQuFKKIq/6t7QI9EJWRlgZc5zeI5zp/YeFAcKiNgpnRDLfnP7XL7y38qx0GfpOS5Tf0joo3Z9bf+wSrhfSIUrPRxGYoH7dcs+TXvdeIlYQ2W+3tblH8vHnbSvgskp59dfVqgi+HvIzpkB5JwWPMAUaC2+wGN/FlRS/WcS3jYTQgn0FT8Q+YDMd/1zhLTSMFaJGcBj0TXV677llZ8WuuNabjxObxa19qyrWHLMRBuz2vP6RFKECHh2y1zxKGn1L1p5HdP5L4uaL+osrsNO2nhMEhFgpwjwSEnZZWw+wh+Jh1JfEe6tSY7iXKPJjdg63kZIACfn5VWiz3kp2u5RoH/wXZN9RG7wVeYAT3J55AZPUIfJt1glG9ee3SUg8s+M/s9zB54X5YDVjm0MXGm4R+5WBKEygGh4KWHLJxRTFT4FjE5zEroDKCtgd2E+PJxM0WXJIUDY3ASRkoaA+x3nZTWs9b4quBk/leZjuVLvCa+zwNH60bDTX2tLJiYCyq8TWTOzLUjlQ+OREbqJpi5E0t38f4lRrRzK3Hkt6XWb3oUeLheWJw81RccipwRKvymvAM5YrYKFncvcKSSaS6mJ982oOSZopx2um/PgIEIkzxZiVPD9q7KTeVg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: grafana-env-secrets
      namespace: monitoring

