apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: grafana-env-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgBPp2RbbBwWiQoA/nw9546TRez5Ir5J6R4/8hW9FI+xba9uiLYqS44Dfw2oPBLsHnUFmUp2G7NnVTJnTIjtm001Y5XcauAaZ6l3Fyoyox9JPWeBiEWKH2dzu/leNlGq7quph/tbrQDrWIqWjjnAeZmIRhBLlPb/l6r+1Jc6ugsqhRyY66cqy37KLCVNzP8tiPrOKnCu2LqCWNaOgtfqhzzxJiRBszZZi1ra65fIm4AXANRstvNYDLxrNwHFMyPKxeFB/3EKkjzJ9X2Uw8VWrIax6MGx07TniaQD8yYw8JZFMpcKttm+vvU5zVCa8zI4SNAO7RzhHNEFBXOLWgYuc2ElTh9xvkJijvL7UVuSao+pLS2I9AyC3hnO5+oOt1E7oiAUUPZhd+Ca7wZ5W2KYjb8a3Ea8pV5cthR6mTeJ4xZfEaLKcrGMh14iH3pp3hTg+fXLsfesxsD3/7WM70L+jvZyOHdLNHrQAF9zKjelvnIwEvaVs7h0cnVkaZBiafzT+qyxH1M8YxCMaSAdBPMsqleb0gkTJHb85AXl+DMwclnbzPgCqmHf4wcdxBtVMe/2aD6ygD7I9SAAeS3F+OYiZqcfQoi9Z86PqdFbO0FTH0WeEAP8VNAXN7Eq+Dw4csG+7fWOZdKdIrjz5Ga0baPRCXMrd2KslLXcNq+fwCN9vq16Fo3BMoIQkxnocH/Pfj/wa1C/D7xqDqxGzLJUMmiLHlEpR2XdL2Ik1cFztEDkljEvJ815MMU=
    GF_AUTH_GITHUB_CLIENT_SECRET: AgAGTazQjqiUKwTe0oI6nZyU+zhkn++m83NfBBsFXMURiu4UHp33u9FQt1J0z53/KV3D9+CCWdwSyOFWAtvFG5KxRj5IuJP4mcSrRrNyny0qtm3irUaaS1QVCbKyQ1Zh88SzXL0qAp+0v1AISzGMr+yTNUCf5UlqUlaZcVdNitc4I3vgDK1gTev1DC1E+vXl5mIbRnYH4yYT12ibkfabm0F5tffK6owQTxRDJHJsOinVqt6Rwp6vfJiBAUBVl61qWfoEltuIDvqkFNHiLciSfQvTNHwFYLtNfrjdbkA0t60yDMxb3yU8MfzntNUzj5q5pEj0SbePTlpCc8tb1JK/p+x7qdx0mcKgB7jJ0giaq1pVKgwOQ6JwxwWjigG9JSYJ7j31jbwM+Jerkv9B+jD9V5Wv6PolYrhMrLIOjrl/9fUZJoJHoUErZmNv+JN8VkSW3UqnTGdYuGLn35GHYq4RGFvzEhcDLF+IZ75FmLDmdOTO2eCQyS6CQga6OPoi3D4WKT4lCMTEdkfRyJOBxY9bIuMvaPsRiWwbVvrM39IkbDr9hXaGX1lXocH0pfWmGxUkSdkZyj/RJulCNz2Hxpx5mvQMsnF9fK86YLqT6Fb1tm7cgPL0wTOaCe1kCC6gX8V7k0Ehe6D2sLjt+DMyJ+OVdHrZTQ3M0R+vYHq0rl9t7YGdBvR7Rxe9sA7I9AV+CBj8kVtJf1bVLIIxB9mgiZux33KopR1MsBY5h1DnlnYtNxqKzLfk5DUhID8w5WIdNg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: grafana-env-secrets
      namespace: monitoring

