apiVersion: v1
kind: Secret
metadata:
  name: grafana-env-secrets
data:
  GF_AUTH_GITHUB_CLIENT_ID: {{ .Values.grafana.giteaClientId | b64enc }}
  GF_AUTH_GITHUB_CLIENT_SECRET: {{ .Values.grafana.giteaClientSecret | b64enc }}
