global:
  rpc:
    host: "deploy.pitz.tech"
    proto: "https"

drone:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: deploy.pitz.tech
    tls:
      - secretName: gitea-tls
        hosts:
          - deploy.pitz.tech

  config:
    gitea:
      enabled: true
      server: https://code.pitz.tech

    blobs:
      endpoint: nyc3.digitaloceanspaces.com
      bucket: mya-drone
      pathStyle: true
      prefix: drone/
      region: nyc3

  image:
    pullPolicy: Always

  litestream:
    enabled: false

    config:
      dbs:
        - path: /data/drone.sqlite
          replicas:
            - type: s3
              bucket: mya-drone
              path: litestream/
              endpoint: nyc3.digitaloceanspaces.com
              region: nyc3

  runners:
    kubernetes:
      enabled: true
      image:
        tag: 1.0.0-beta.6

  redis-queue:
    enabled: true
