trailingComma: "es5"
tabWidth: 4
semi: true
singleQuote: false
printWidth: 120

overrides:
  - files:
      - "*.md"
    options:
      proseWrap: always

  - files:
      - "*.json"
      - "*.yaml"
      - "*.yml"
      - "*.md"
    options:
      tabWidth: 2
