apiVersion: v2
type: application
name: gitea
description: |
  Git with a cup of tea. A painless, self-hosted Git Service.
sources:
  - https://github.com/go-gitea/gitea
  - https://github.com/mjpitz/mjpitz/tree/main/charts/gitea
maintainers:
  - name: Mya Pitzeruse
    url: https://mya.sh
version: 23.12.6
appVersion: 1.21.6
dependencies:
  - name: litestream
    version: 22.4.5
    repository: https://mya.sh
    condition: litestream.enabled
  - name: redis-queue
    version: 22.4.6
    repository: https://mya.sh
    condition: redis-queue.enabled
  - name: redis
    version: 22.4.10
    repository: https://mya.sh
    condition: redis.enabled
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: FD0F1E353074E15A4883BC630FCA5E3C09DFB314
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0fca5e3c09dfb314
