ingress-nginx:
  controller:
    kind: DaemonSet
    service:
      externalTrafficPolicy: Local
    admissionWebhooks:
      enabled: false
    config:
      use-forwarded-headers: "true"
    extraArgs:
      enable-ssl-passthrough: "true"
    ingressClass: nginx
    publishService:
      enabled: true
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
  defaultBackend:
    enabled: true
    replicaCount: 1
