{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litestream.fullname" . }}-config
data:
  litestream.yml: {{ include "litestream.config" . | b64enc }}
{{- end }}
