{{- $netV1 := semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
{{- $netV1beta := semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
{{- range $alias := .Values.aliases }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $alias.name }}
spec:
  type: ExternalName
  externalName: {{ $alias.backend.address }}
  ports:
    - port: {{ $alias.backend.port | default 443 }}
      targetPort: {{ $alias.backend.port | default 443 }}
      name: http
---
{{- if $netV1 }}
apiVersion: networking.k8s.io/v1
{{- else if $netV1beta }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $alias.name }}
  annotations:
    kubernetes.io/ingress.class: {{ $alias.ingress.class | default "nginx" | quote }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ $alias.tls.issuer.name | default "letsencrypt-prod" | quote}}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "{{ $alias.backend.protocol | default "https" }}://{{ $alias.backend.address }}:{{ $alias.backend.port | default 443 }}/$1"
spec:
  tls:
    - hosts:
        - {{ $alias.ingress.address }}
      secretName: {{ $alias.name }}-certs
  rules:
    - host: {{ $alias.ingress.address }}
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            {{- if $netV1 }}
            backend:
              service:
                name: {{ $alias.name }}
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: {{ $alias.name }}
              servicePort: http
            {{- end }}
{{- end }}
