external-dns:
  logLevel: debug
  domainFilters:
    - deps.cloud
    - mjpitz.com
    - mya.sh
    - pitz.tech
  txtOwnerId: "mya-nyc"
  txtPrefix: "mya-nyc."
  policy: sync
  provider: cloudflare
  cloudflare:
    secretName: "cloudflare-api-token"
    proxied: false

cloudflare:
  apiToken: ""
