apiVersion: v2
type: application
name: kubernetes
description: Deploy the Drone.IO Kubernetes Runner.
sources:
  - https://github.com/mjpitz/mjpitz/tree/main/charts/drone
maintainers:
  - name: Mya Pitzeruse
    url: https://mjpitz.com
version: 0.0.0
appVersion: latest
