{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-config
data:
  redis.conf: {{ include "redis.config" . | b64enc | quote }}
{{- end }}
{{- if .Values.cluster.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-cluster-config
data:
  envoy.yaml: {{ include "redis.cluster.config" . | b64enc | quote }}
{{- end }}
