apiVersion: 1

deleteDatasources: []
  # - name: ResumeDB
  # - name: UserDB
  # - name: AppTraxDB
  # - name: GraphQL API

datasources:
  # https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      host: metrics-clickhouse
      username: clickhouse
      secure: false
      protocol: native
      logs:
        defaultDatabase: otel
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
        durationUnit: milliseconds
    secureJsonData:
      password: clickhouse
