apiVersion: v2
type: application
name: drone
description: |
  Easily deploy a Drone.IO, a container-native, continuous delivery platform. This chart provisions a Drone server
  instance intended for smaller
sources:
  - https://github.com/harness/drone
  - https://github.com/mjpitz/mjpitz/tree/main/charts/drone
maintainers:
  - name: Mya Pitzeruse
    url: https://mjpitz.com
version: 22.5.6
appVersion: 2.11.1
dependencies:
  - name: litestream
    version: 22.4.2
    repository: https://mjpitz.com
    condition: litestream.enabled
  - name: redis-queue
    version: 22.4.4
    repository: https://mjpitz.com
    condition: redis-queue.enabled
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: FD0F1E353074E15A4883BC630FCA5E3C09DFB314
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0fca5e3c09dfb314
