apiVersion: v2
type: application
name: drone
description: |
  Easily deploy a Drone.IO, a container-native, continuous delivery platform. This chart provisions a Drone server 
  instance intended for smaller
sources:
  - https://github.com/harness/drone
  - https://github.com/mjpitz/mjpitz/tree/main/charts/drone
maintainers:
  - name: Mya Pitzeruse
    url: https://mjpitz.com
version: 22.5.0
appVersion: 2.11.1
dependencies:
  - name: litestream
    version: 22.4.0
    repository: https://mjpitz.com
    condition: litestream.enabled

  - name: redis-queue
    version: 22.4.0
    repository: https://mjpitz.com
    condition: redis-queue.enabled
