{{- $fullname := include "12factor.fullname" . }}
{{- $labels := include "12factor.labels" . }}
{{- $image := .Values.image }}
{{- $deployment := .Values.deployment }}
{{- range .Values.deployment.tasks }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-task-%s" $fullname .name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  schedule: {{ .schedule | quote }}
  suspend: {{ .suspend }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: {{ printf "task-%s" .name }}
        {{- $labels | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: {{ printf "task-%s" .name }}
            {{- $labels | nindent 12 }}
        spec:
          containers:
            - name: {{ .name }}
              {{- if .securityContext }}
              securityContext:
                {{- toYaml .securityContext | nindent 16 }}
              {{- else }}
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
              {{- end }}
              image: "{{ $image.repository }}:{{ $image.tag }}"
              imagePullPolicy: {{ $image.pullPolicy }}
              {{- with .env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with $deployment.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $deployment.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $deployment.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
