{{- $networking := .Values.networking -}}
{{- if $networking.ingress.enabled -}}
{{- $fullName := include "12factor.fullname" . -}}
{{- if and $networking.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) -}}
  {{- if not (hasKey $networking.ingress.annotations "kubernetes.io/ingress.class") -}}
  {{- $_ := set $networking.ingress.annotations "kubernetes.io/ingress.class" $networking.ingress.className -}}
  {{- end -}}
{{- end -}}
{{- $v1Networking := semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
{{- if $v1Networking -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "12factor.labels" . | nindent 4 }}
  {{- with $networking.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $networking.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $networking.ingress.className }}
  {{- end }}
  {{- if $networking.ingress.tls }}
  tls:
    {{- range $networking.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $networking.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if $v1Networking }}
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .portName | default $networking.ingress.portName }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .portName | default $networking.ingress.portName }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
