apiVersion: v1
kind: Service
metadata:
  name: {{ include "12factor.fullname" . }}
  labels:
    app.kubernetes.io/component: app
    {{- include "12factor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.service.type }}
  clusterIP: {{ .Values.networking.service.clusterIP }}
  ports:
    {{- .Values.networking.service.ports | toYaml | nindent 4 }}
  selector:
    app.kubernetes.io/component: app
    {{- include "12factor.selectorLabels" . | nindent 4 }}
