---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-configd
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
{{- with .Values.extra.config }}
data:
  {{- range $key, $value := . }}
  {{ $key | quote }}: {{ $value | b64enc }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
