# TODO: look at moving some of this into XML or YAML. See link below.
#       https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.yaml.example
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-env
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  CLICKHOUSE_DB: {{ print "default" | b64enc | quote }}
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: {{ print "1" | b64enc | quote }}
  CLICKHOUSE_USER: {{ .Values.auth.username | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
