apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: http
    - name: clickhouse
      protocol: TCP
      port: 9000
      targetPort: clickhouse
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
