apiVersion: v2
type: application
name: renovate
version: 23.10.0
dependencies:
  - name: renovate
    repository: file://../../../charts/renovate
    version: "*"
    alias: "gitea"
  - name: renovate
    repository: file://../../../charts/renovate
    version: "*"
    alias: "c8labs"
