{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maddy.fullname" . }}-config
data:
  maddy.conf: {{ include "maddy.config" . | b64enc | quote }}
{{- end }}
{{- if .Values.mta_sts.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maddy.fullname" . }}-nginx-config
data:
  nginx.conf: {{ include "maddy.nginx" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maddy.fullname" . }}-well-known-config
data:
  mta-sts.txt: {{ include "maddy.well-known.mta-sts" . | b64enc | quote }}
{{- end }}
{{- if .Values.rspamd.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maddy.fullname" . }}-rspamd-overrides
data:
  {{- range $key, $value := .Values.rspamd.config }}
  {{ $key }}: {{ b64enc $value | quote }}
  {{- end }}
{{- end }}
