---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes.fullname" . }}-config
data:
  DRONE_RPC_SECRET: {{ .Values.config.rpc.secret | default .Values.global.rpc.secret | b64enc | quote }}
  DRONE_RPC_HOST: {{ .Values.config.rpc.host | default .Values.global.rpc.host | b64enc | quote }}
  DRONE_RPC_PROTO: {{ .Values.config.rpc.proto | default .Values.global.rpc.proto | default "http" | b64enc | quote }}
  {{- range $key, $value := .Values.config.overrides }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
