{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storj.fullname" . }}-sidecar-config
data:
  {{ .Values.externalConfig.secretRef.accessKeyName }}: {{ .Values.config.accessKeyId | b64enc | quote }}
  {{ .Values.externalConfig.secretRef.secretKeyName }}: {{ .Values.config.secretAccessKey | b64enc | quote }}
  {{ .Values.externalConfig.secretRef.accessGrantName }}: {{ .Values.config.accessGrant | b64enc | quote }}
{{- end }}
