apiVersion: v1
kind: Secret
metadata:
  name: grafana-env-secrets
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ .Values.cognative.grafana.oauth.clientId | b64enc }}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.cognative.grafana.oauth.clientSecret | b64enc }}
