{{- $redisConfig := dict "Chart" (dict "Name" "redis") "Values" .Values.redis "Release" .Release -}}
{{- $storjConfig := dict "Chart" (dict "Name" "storj") "Values" .Values.storj "Release" .Release -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "registry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: debug
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          command:
            - sh
          args:
            - -c
            - |
              env -i /bin/registry serve /etc/docker/registry/config.yml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/docker/registry
              name: config
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.ui.enabled }}
        - name: ui
          image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          {{- if or .Values.ui.config.auth.basic.username .Values.ui.config.auth.token.username }}
          envFrom:
            - secretRef:
                name: {{ include "registry.fullname" . }}-ui-config
          {{- end }}
          env:
            - name: PORT
              value: "5002"
            - name: DOCKER_REGISTRY_URL
              value: http://127.0.0.1:5000
            - name: PUBLIC_REGISTRY_URL
              value: {{ .Values.ui.config.domain | quote }}
          ports:
            - name: web
              containerPort: 5002
              protocol: TCP
        {{- end }}
        {{- if .Values.redis.enabled }}
        {{- include "redis.cluster.container" $redisConfig | nindent 8 }}
        {{- end }}
        {{- if .Values.storj.enabled }}
        {{- include "storj.container" $storjConfig | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            {{- if .Values.externalConfig.secretRef.name }}
            secretName: {{ .Values.externalConfig.secretRef.name }}
            {{- else }}
            secretName: {{ include "registry.fullname" . }}-config
            {{- end }}
        {{- if .Values.redis.enabled }}
        {{- include "redis.cluster.volume" $redisConfig | nindent 8 }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
