{{- if .Values.ingress.enabled -}}
{{- $authEnabled := .Values.auth.enabled }}
{{- $authFullName := dict "Chart" (dict "Name" "auth") "Values" .Values.redis "Release" .Release | include "auth.fullname" -}}
{{- $registryFullName := include "registry.fullname" . -}}
{{- $uiEnabled := .Values.ui.enabled -}}
{{- $v1Networking := semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
{{- if $v1Networking -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $registryFullName }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if $v1Networking }}
          {{- if $authEnabled }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ $authFullName }}
                port:
                  name: http
          - path: /google_auth
            pathType: Prefix
            backend:
              service:
                name: {{ $authFullName }}
                port:
                  name: http
          - path: /github_auth
            pathType: Prefix
            backend:
              service:
                name: {{ $authFullName }}
                port:
                  name: http
          {{- end }}
          # /v2/ must go to the docker-registry
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: {{ $registryFullName }}
                port:
                  name: http
          {{- if $uiEnabled }}
          # send the rest to the ui
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $registryFullName }}
                port:
                  name: web
          {{- end }}
        {{- else }}
          {{- if $authEnabled }}
          - path: /auth
            backend:
              serviceName: {{ $authFullName }}
              servicePort: 5001
          - path: /google_auth
            backend:
              serviceName: {{ $authFullName }}
              servicePort: 5001
          - path: /github_auth
            backend:
              serviceName: {{ $authFullName }}
              servicePort: 5001
          {{- end }}
          # /v2/ must go to the docker-registry
          - path: /v2/
            backend:
              serviceName: {{ $registryFullName }}
              servicePort: 5000
          {{- if $uiEnabled }}
          # send the rest to the ui
          - path: /
            backend:
              serviceName: {{ $registryFullName }}
              servicePort: 5002
          {{- end }}
        {{- end }}
    {{- end }}
  {{- end }}
