{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-config
data:
  config.yml: {{ include "registry.config" . | b64enc | quote }}
{{- end }}
{{- if or .Values.ui.config.auth.basic.username .Values.ui.config.auth.token.username | and .Values.ui.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-ui-config
data:
  {{- if .Values.ui.config.auth.basic.username }}
  BASIC_AUTH_USER: {{ .Values.ui.config.auth.basic.username | b64enc | quote }}
  BASIC_AUTH_PASSWORD: {{ .Values.ui.config.auth.basic.password | b64enc | quote }}
  {{- else if .Values.ui.config.auth.token.username }}
  TOKEN_AUTH_USER: {{ .Values.ui.config.auth.token.username | b64enc | quote }}
  TOKEN_AUTH_PASSWORD: {{ .Values.ui.config.auth.token.password | b64enc | quote }}
  {{- end }}
{{- end }}
