{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-config
data:
  config.yml: {{ include "registry.config" . | b64enc | quote }}
{{- end }}
