apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
    - port: 5001
      targetPort: debug
      protocol: TCP
      name: debug
    {{- if .Values.ui.enabled }}
    - port: 5002
      targetPort: web
      protocol: TCP
      name: web
    {{- end }}
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
