12factor:
  fullnameOverride: catalog

  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.2.0

  deployment:
    replicaCount: 1

    application:
      env:
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "pitz.tech"
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "https://cloud.pitz.tech/oauth2/callback"
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://127.0.0.1:8090"
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: "http://0.0.0.0:8080"
      envFrom:
        - secretRef:
            name: catalog-config
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      resources: {}

    sidecars:
      - name: catalog
        image:
          repository: img.pitz.tech/mya/catalog
          tag: 22.5.0-alpine
          pullPolicy: IfNotPresent
        ports:
          - name: catalog
            containerPort: 8090
            protocol: TCP
        args:
          - -bind_address
          - 127.0.0.1:8090
        resources: {}

  networking:
    service:
      ports:
        - name: http
          targetPort: http
          port: 80
          protocol: TCP

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: cloud.pitz.tech
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: catalog-tls
          hosts:
            - cloud.pitz.tech
