apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "renovate.fullname" . }}
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedule | quote }}
  {{- with .Values.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  suspend: {{ .Values.suspend | toString }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | default 1 }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default 3 }}
  jobTemplate:
    metadata:
      labels:
          {{- include "renovate.labels" . | nindent 10 }}
    spec:
      template:
        metadata:
          annotations:
            checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
            {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          labels:
            {{- include "renovate.labels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "renovate.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                {{- with .Values.env }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              {{- if .Values.github.token | or .Values.envFrom }}
              envFrom:
                {{- if .Values.github.token }}
                - secretRef:
                    name: {{ include "renovate.fullname" . }}-env
                {{- end }}
                {{- with .Values.envFrom }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - mountPath: /opt/renovate/
                  name: config
                  readOnly: true
                - mountPath: /tmp/renovate/
                  name: scratch
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: config
              secret:
                {{- if .Values.externalConfig.secretRef.name }}
                secretName: {{ .Values.externalConfig.secretRef.name }}
                {{- else }}
                secretName: {{ include "renovate.fullname" . }}
                {{- end }}
            - name: scratch
              emptyDir: {}
