{{- if .Values.github.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renovate.fullname" . }}-env
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:
  GITHUB_COM_TOKEN: {{ .Values.github.token | b64enc }}
{{- end }}

{{- if not .Values.externalConfig.secretRef.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renovate.serviceAccountName" . }}
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.config | toJson | b64enc }}
{{- end }}
