{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone.fullname" . }}-config
data:
  drone.env: {{ include "drone.config" . | b64enc | quote }}
{{- end }}
