apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone.fullname" . }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.litestream.enabled | and .Values.litestream.metrics.enabled }}
    - port: {{ .Values.litestream.metrics.port }}
      targetPort: litestream
      protocol: TCP
      name: litestream
    {{- end }}
  selector:
    {{- include "drone.selectorLabels" . | nindent 4 }}
