apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.clickhouse.fullname" . }}-configd
  labels:
    {{- include "metrics.labels" (dict "component" "clickhouse" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  docker.xml: {{ include "metrics.clickhouse.dockerConfig" . | b64enc | quote }}
  s3.xml: {{ include "metrics.clickhouse.s3Config" . | b64enc | quote }}
  user_directories.xml: {{ include "metrics.clickhouse.userDirectoriesConfig" . | b64enc | quote }}
