apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.clickhouse.fullname" . }}-users
  labels:
    {{- include "metrics.labels" (dict "component" "clickhouse" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  admin.xml: {{ include "metrics.clickhouse.adminUser" . | b64enc | quote }}
  profiles.xml: {{ include "metrics.clickhouse.profiles" . | b64enc | quote }}
