apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.clickhouse.fullname" . }}-init
  labels:
    {{- include "metrics.labels" (dict "component" "clickhouse" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  init.sql: {{ include "metrics.clickhouse.initSql" . | b64enc | quote }}
  CLICKHOUSE_ADMIN_USER: {{ .Values.clickhouse.admin.username | b64enc | quote }}
  CLICKHOUSE_ADMIN_PASSWORD: {{ .Values.clickhouse.admin.password | b64enc | quote }}
