apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.grafana.fullname" . }}-config
  labels:
    {{- include "metrics.labels" (dict "component" "grafana" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  grafana.ini: {{ include "metrics.grafana.ini" . | b64enc | quote }}
  clickhouse.yaml: {{ include "metrics.grafana.datasource" . | b64enc | quote }}
  {{- if .Values.grafana.extraDatasources }}
  extras.yaml: {{ include "metrics.grafana.extraDatasources" . | b64enc | quote }}
  {{- end }}
  GF_INSTALL_PLUGINS: {{ join "," .Values.grafana.plugins | b64enc | quote }}
  GF_PATHS_PROVISIONING: {{ "/etc/grafana/provisioning" | b64enc | quote }}
