apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.iceberg.fullname" . }}-config
  labels:
    {{- include "metrics.labels" (dict "component" "iceberg" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: {{ include "metrics.iceberg.config" . | b64enc | quote }}
