apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics.iceberg.fullname" . }}
  labels:
    {{- include "metrics.labels" (dict "component" "iceberg" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    {{- include "metrics.selectorLabels" (dict "component" "iceberg" "root" .) | nindent 4 }}
