apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics.iceberg.serviceAccountName" . }}
  labels:
    {{- include "metrics.labels" (dict "component" "iceberg" "root" .) | nindent 4 }}
  {{- $common := .Values.commonAnnotations | default dict }}
  {{- with mergeOverwrite (deepCopy $common) (.Values.iceberg.serviceAccount.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics.clickhouse.serviceAccountName" . }}
  labels:
    {{- include "metrics.labels" (dict "component" "clickhouse" "root" .) | nindent 4 }}
  {{- with mergeOverwrite (deepCopy $common) (.Values.clickhouse.serviceAccount.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics.grafana.serviceAccountName" . }}
  labels:
    {{- include "metrics.labels" (dict "component" "grafana" "root" .) | nindent 4 }}
  {{- with mergeOverwrite (deepCopy $common) (.Values.grafana.serviceAccount.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics.valkey.cache.serviceAccountName" . }}
  labels:
    {{- include "metrics.labels" (dict "component" "cache" "root" .) | nindent 4 }}
  {{- with mergeOverwrite (deepCopy $common) (.Values.grafana.cache.serviceAccount.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
