apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics.valkey.cache.fullname" . }}
  labels:
    {{- include "metrics.labels" (dict "component" "cache" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: valkey
      port: 6379
      protocol: TCP
      targetPort: valkey
  selector:
    {{- include "metrics.selectorLabels" (dict "component" "cache" "root" .) | nindent 4 }}
