apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.valkey.cache.fullname" . }}-config
  labels:
    {{- include "metrics.labels" (dict "component" "cache" "root" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  valkey.conf: {{ include "metrics.valkey.cache.config" . | b64enc | quote }}
