apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-credentials
data:
  AWS_ACCESS_KEY_ID: {{ .Values.backup.accessKeyID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.secretAccessKey | b64enc }}
  AWS_ENDPOINTS: {{  .Values.backup.endpoint | b64enc }}
  VIRTUAL_HOSTED_STYLE: {{ b64enc "true" }}
