apiVersion: v2
type: application
name: redis
description: |
  Deploy a highly-available, partition-tolerant Redis cluster fronted by an envoy sidecar. Envoy partitions keys among
  members of the cluster using a consistent hashing algorithm making it great as a best-effort cache.
sources:
  - https://github.com/redis/redis
  - https://github.com/envoyproxy/envoy
  - https://github.com/mjpitz/mjpitz/tree/main/charts/redis
maintainers:
  - name: Mya Pitzeruse
    url: https://mya.sh
version: 22.4.10
appVersion: 6.2.6
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: FD0F1E353074E15A4883BC630FCA5E3C09DFB314
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0fca5e3c09dfb314
