# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- The number of redis instances to deploy.
replicaCount: 1

# -- Configure how the redis cluster will be deployed. This can be Deployment, DaemonSet, or StatefulSet.
kind: Deployment

# -- Configure the update strategy to use.
updateStrategy: {}

image:
  # -- The repository hosting the image.
  repository: img.pitz.tech/mya/redis
  # -- The pull policy to use for the image.
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: 6.2.7-alpine

# -- Specify the secret containing the registry credentials.
imagePullSecrets: []
# -- Override the name of the release.
nameOverride: ""
# -- Override the full name of the release.
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Annotations to add to the service account.
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname
  #    template.
  name: ""

# -- Annotations to add to the pod, typically used for assume roles.
podAnnotations: {}

# -- Specify the security context for the entire pod.
podSecurityContext: {}
  # fsGroup: 2000

# -- Specify the security context for the `redis` container.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Specify the resources for the pod.
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  # -- Enable autoscaling for the deployment.
  enabled: false
  # -- Specify the minimum number of replicas.
  minReplicas: 1
  # -- Specify the maximum number of replicas.
  maxReplicas: 100
  # -- Specify the percent CPU utilization that causes the pods to autoscale.
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Specify the node selector used to control which nodes pods are deployed to.
nodeSelector: {}

# -- Specify taints that the pods are willing to tolerate.
tolerations: []

# -- Specify affinity rules for the pods.
affinity: {}

metrics:
  serviceMonitor:
    # -- Add a Prometheus ServiceMonitor that scrapes the service.
    enabled: false
    # -- How frequently Prometheus should pull metrics from the service.
    interval: 10s

# -- When using a StatefulSet, persistent volume claim templates can be specified for writing data to disk.
volumeClaimTemplates: []
#  - metadata:
#      name: data
#    spec:
#      accessModes:
#        - ReadWriteOnce
#      resources:
#        requests:
#          storage: 10Gi
#      storageClassName: ""

# -- Add additional volumes to the pod.
extraVolumes: []
#  - name: data
#    emptyDir: {}

# -- Add additional volume mounts to the pod.
extraVolumeMounts: []
#  - name: data
#    mountPath: /data
#    readOnly: false

externalConfig:
  secretRef:
    # -- Specify the name of the secret containing the raw configuration.
    name: ""

config:
  # -- How many databases to make available.
  databases: 1

  maxMemory:
    # -- The number of bytes representing the maximum amount of memory that can be consumed.
    size: ""
    # -- The eviction policy to use when the maximum memory is reached or exceeded.
    evictionPolicy: allkeys-lru

  data:
    # -- Where the append-only file and snapshots should be stored.
    directory: ""
    appendOnlyFile:
      # -- Whether to enable an append-only file.
      enabled: false
      # -- When fsyncs should occur when using an append-only file.
      fsync: everysec
    snapshot:
      # -- Whether to enable snapshots.
      enabled: false
      # -- When to take a snapshot. [ seconds, key changes ]
      schedules:
        - [3600, 1]   #   * After 3600 seconds (an hour) if at least 1 key changed
        - [300, 100]  #   * After 300 seconds (5 minutes) if at least 100 keys changed
        - [60, 10000] #   * After 60 seconds if at least 10000 keys changed
      # -- Compress the snapshot.
      compression: true

  # -- Specify the username used for authentication.
  username: ""
  # -- Specify the password used for authentication.
  password: ""

cluster:
  # -- Enable the Envoy cluster.
  enabled: true

  image:
    # -- The repository hosting the Envoy proxy.
    repository: envoyproxy/envoy
    # -- The pull policy used when pulling the Envoy proxy.
    pullPolicy: IfNotPresent
    # -- The version of Envoy to run.
    tag: "v1.21-latest"
