---
apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-agent-secret
{{- if not .Values.woodpecker.agent.secret }}
data: {}
{{- else }}
data:
  {{- range $key, $value := .Values.woodpecker.agent.secret }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-secret
{{- if not .Values.woodpecker.server.secret }}
data: {}
{{- else }}
data:
  {{- range $key, $value := .Values.woodpecker.server.secret }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}
