registry:
  replicaCount: 2

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    hosts:
      - host: img.pitz.tech
    tls:
      - secretName: registry-tls
        hosts:
          - img.pitz.tech

  extraVolumes:
    - name: token-cert
      secret:
        secretName: registry-auth-token-cert

  extraVolumeMounts:
    - name: token-cert
      mountPath: /etc/docker/auth/token
      readOnly: true

  metrics:
    serviceMonitor:
      enabled: true

  config:
    storage:
      s3:
        region: "nyc3"
        regionendpoint: "nyc3.digitaloceanspaces.com"
        bucket: "mya-images"
        encrypt: false
        secure: true
      maintenance:
        uploadpurging:
          enabled: false

  auth:
    enabled: true
    replicaCount: 2

    token:
      cert: ""
      key: ""

    extraVolumes:
      - name: token-cert
        secret:
          secretName: registry-auth-token-cert

    extraVolumeMounts:
      - name: token-cert
        mountPath: /etc/docker/auth/token
        readOnly: true

    config:
      token:
        expiration: 86400
        autoRedirect: true
        realm: "https://img.pitz.tech/auth"
        service: "img.pitz.tech"
        issuer: "Registry Auth"
        certificate: "/etc/docker/auth/token/tls.crt"
        key: "/etc/docker/auth/token/tls.key"

      acl:
        - actions: [ "*" ]
          comment: The web user can query the api
          match: { account: "web" }
        # mya
        - actions: [ "*" ]
          comment: mya can push and pull her images
          match: { account: "mya", name: mya/* }
        - actions: [ "*" ]
          comment: mya can push and pull woodpeckerci images
          match: { account: "mya", name: woodpeckerci/* }
        - actions: [ "*" ]
          comment: mya can push and pull dreamboothy images
          match: { account: "mya", name: dreamboothy/* }
        # dreamboothy
        - actions: [ "*" ]
          comment: dreamboothy can push and pull their images
          match: { account: "dreamboothy", name: dreamboothy/* }
        # depscloud
        - actions: [ "*" ]
          comment: depscloud can push and pull their images
          match: { account: "depscloud", name: depscloud/* }
        # anonymous
        - actions: [ "pull" ]
          comment: Anonymous users can pull depscloud
          match: { account: "", name: depscloud/* }
        - actions: [ "pull" ]
          comment: Anonymous users can pull mya
          match: { account: "", name: mya/* }
        - actions: [ "pull" ]
          comment: Anonymous users can pull woodpeckerci images
          match: { account: "", name: woodpeckerci/* }

      # htpasswd -nbB username password
      users:
        "": { }
        depscloud:
          password: $2y$05$mhfW7VdH9O1xh6Qte6tmi.lpIfT/csuDO4dvbxpQE6i8LB/X.W6Hu
        dreamboothy:
          password: $2y$05$ku.LYGK6oIm84INyhnWqCex/50tBc6ZB78.yylT4T8xnZNDEh2ItC
        mya:
          password: $2y$05$o5SeZ.Ux/KhyxJb.0tNgIOwop9ma3bldtCQVbjwgIjNs3AOA1wmH.
        web:
          password: $2y$05$UWVnmRVM98v9H55bdfJa8uItWG0s3UtYKi04CncTgSmkpVjaGBR2i

  redis:
    enabled: true
    replicaCount: 3

    metrics:
      serviceMonitor:
        enabled: true

  ui:
    enabled: true

    config:
      domain: img.pitz.tech
      auth:
        token:
          username: web
          password: ""
