name: charts-publish

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/charts-publish.yaml
      - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.4.1

      - name: Prepare GPG key
        run: |
          mkdir .cr-gpg

          keyring=".cr-gpg/secring.gpg"
          base64 -d <<< "$GPG_KEYRING_BASE64" > "$keyring"

          passphrase_file=".cr-gpg/passphrase"
          echo "$GPG_PASSPHRASE" > "$passphrase_file"
          
          echo "CR_PASSPHRASE_FILE=$passphrase_file" >> "$GITHUB_ENV"
          echo "CR_KEYRING=$keyring" >> "$GITHUB_ENV"
        env:
          GPG_KEYRING_BASE64: "${{ secrets.GPG_KEYRING_BASE64 }}"
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          config: charts/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
