name: charts-trigger-deploy

# This workflow triggers a site deployment when the Helm chart index.yaml is updated
# by the charts-publish workflow

on:
  push:
    branches:
      - main
    paths:
      - site/public/index.yaml

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger site deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: charts-updated
          
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build
        env:
          HUGO_VERSION: 0.69.1
          HUGO_ENV: production
        run: |
          make site/deps site/build site/test

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mjpitz
          directory: ./site/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
