name: infra-terraform-apply

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/infra-terraform.yaml
      - infra/do/**
      - infra/helm/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/infra-terraform.yaml
      - infra/do/**
      - infra/helm/**

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}"
      DIGITALOCEAN_ACCESS_TOKEN: "${{ secrets.TERRAFORM_DIGITALOCEAN_ACCESS_TOKEN }}"
      SPACES_ACCESS_KEY_ID: "${{ secrets.TERRAFORM_SPACES_ACCESS_KEY_ID }}"
      SPACES_SECRET_ACCESS_KEY: "${{ secrets.TERRAFORM_SPACES_SECRET_ACCESS_KEY }}"
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/helm

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra/helm

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply --auto-approve
        working-directory: ./infra/helm
