name: pages-build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/site.yaml
      - content/**
      - layouts/**
      - resources/**
      - static/**
      - themes/**
      - config.toml
  push:
    branches:
      - main
    paths:
      - .github/workflows/site.yaml
      - content/**
      - layouts/**
      - resources/**
      - static/**
      - themes/**
      - config.toml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Vendor tooling
        uses: mjpitz/bin-vendor@main

      - name: Build
        env:
          HUGO_VERSION: 0.69.1
          HUGO_ENV: production
        run: |
          make build test

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: false
          keep_files: true # otherwise, we remove the index.yaml file
