name: pages-build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/pages-build.yaml
      - site/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/pages-build.yaml
      - site/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          make site/deps site/build site/test

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./site/dist --project-name=mjpitz
