{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-config
data:
  app.ini: {{ include "gitea.config" . | b64enc | quote }}
{{- end }}
