{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gitea.fullname" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.metrics.serviceMonitor.interval }}
      path: /metrics
      port: http
    {{- if .Values.litestream.enabled | and .Values.litestream.metrics.enabled | and .Values.litestream.metrics.serviceMonitor.enabled }}
    - interval: {{ .Values.litestream.metrics.serviceMonitor.interval }}
      path: /metrics
      port: litestream
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "gitea.selectorLabels" . | nindent 6 }}
{{- end }}
